name: Run Automated Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-suite:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      run: echo "Hllo"
#test
# CODEOWNERS test
